CREATE DATABASE crud;
USE crud;

CREATE TABLE user (
    id VARCHAR(20) NOT NULL UNIQUE,
    PASSWORD VARCHAR (255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    CONSTRAINT user_pk PRIMARY KEY(id)
);

Select * FROM user;